### ISSUE TITLE
Configuration Specification

### ISSUE THREAD

**Issue by AustinTSchaffer** [o3-cloud/cllm#7]
https://github.com/o3-cloud/cllm/blob/6dfb0d1043dbd35903a76be4a00f2f00736e1eb3/cllm/cllm.py#L210

For all of these configuration settings, I feel like the order of precedence should be swapped. The way I've typically seen these kinds of things configured, and how I normally go about it:

- make a `constants.py` file which reads in all of the environment variables that your app supports
- reference those constants everywhere, using them as default values
- allow users to override the defaults with the CLI args

Currently it seems to ignore the CLI args if the relevant environment variable is set.

**Comment by AgentO3** [comment]
I patterned it based on terraform's variable precedence where ENV takes precedence over cli args. Doing some quick research what you suggest is the accepted standard.
